title: 성장하는 개발자, 호돌이
subtitle: 호돌이 since 2020.12
description: >- # this means to ignore newlines until "baseurl:"
  성장하는 개발자, 호돌이

url: "https://hoyeonhwang.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Contact
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: hoyeon.jpg
author: HoYeon Hwang
author_bio: Hi, my name HoYeon Hwang :D
author_email: "hoyun7443@naver.com"
author_location: South Korea
author_website_url: "https://hoyeonhwang.github.io/"
typewrite-text: We live in a twilight world.

# Experiences
author_work_experiences:
            #- company_name: Google
            #  company_logo: google.png
            #  company_url: https://google.com
            #  designation: Software Engineer
            #  description: Worked on various Google Products
            #  visibility: true
# Education
author_education_details:
              - college_logo: SSAFY_logo.png
                college_name: 삼성 청년SW 아카데미
                college_url: https://ssafy.com
                college_degree: student
                description: Bachelor of Technology
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: SPRING_logo.png
                project_title: 스프링 기반 웹 기초
                project_description: 스프링프레임워크를 기반으로하여 웹의 기초를 공부하고 있고 VUE와 REACT등을 공부하고 있습니다.
                project_url: https://spring.io/
                visibility: true
              - project_thumbnail: ALGO_logo.png
                project_title: 알고리즘
                project_description: 다양한 알고리즘 기법을 차근차근 해결해 나가며 학습하고 있습니다.
                project_url: https://www.acmicpc.net/user/hoyun7443
                visibility: true

# social links
twitter_username: hoyun7443
github_username:  HoYeonHwang
facebook_username: hoyun7443
linkedin_username: null
behance_username: null
instagram_username: hoyun7443
medium_username: null
telegram_username: null
dribbble_username: null
flickr_username: null

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: hoyun7443

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://

# formspree (contact form)
formspree_email: hoyun7443@naver.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
